* Uploading a csv data 
clear all 
set more off 

*check current directory
cd 

*Set to new directory  
cd "C:\Users\mawus\Desktop\STATA\LEarning Stata" // set to desired directory 

*Load data (csv)
insheet using intro_hs0.csv, clear 
// use intro_hs0 for .dta(stat) file or if from a web, use nameofwebsite 

br // view data 
list in 1/10 // list first 10 observation 
describe 

* Summary statistics 
 summ gender race ses schtyp prgtype read write math science socst
 
* summerizing by program type 
tab prgtype
bysort prgtype: summ ses read write math science

* Correlation matrix 
cor ses read write math science socst

* scatter diagrames: first encode prgtype, gen (prgtype1)
encode prgtype, gen (prgtype1)
twoway scatter math prgtype1
twoway scatter socst math
twoway scatter socst math

* creating automatic dummies for prgrtype 
sort prgtype
xi, prefix() i.prgtype

* regression 
 reg socst race science math write read _Iprgtype_2 _Iprgtype_3
 
* alternative regression with autogenerated dummies for prgtype
xi: reg socst race science math write read i.prgtype

** t-Test and comparing means 
ttest math=80
ttest math=write


 
